### ISSUE TITLE
Fixed Nav Bar

### ISSUE THREAD

**Issue by yousefsayedd1** [behnamazimi/practical-front-end-projects#14]
You need to make the nav bar fixed so that if the user scroll deep and decide to search, he doesn't have to go all the way up.
Can you assign it to me?

**Comment by behnamazimi** [comment]
Hey @yousefsayedd1 
Which app are you talking about?

**Comment by behnamazimi** [comment]
Feel free to send a PR.

**Comment by leoimewore** [comment]
I get working on this. @behnamazimi

**Comment by leoimewore** [comment]
Sent a pull request. Please review

**Comment by yousefsayedd1** [comment]
@behnamazimi  I sent a PR.

**Comment by behnamazimi** [comment]
Thanks for the contribution @yousefsayedd1 :)

**Comment by yousefsayedd1** [comment]
@behnamazimi  Thank you for your help :) it's my first PR so I am happy that I did it XD
