### ISSUE TITLE
Next Page button 

### ISSUE THREAD

**Issue by yousefsayedd1** [behnamazimi/practical-front-end-projects#15]
It will be better if you reposition the Next Page button on the right side

**Comment by yousefsayedd1** [comment]
@behnamazimi  can you assign it to me

**Comment by behnamazimi** [comment]
Hey @yousefsayedd1 
Which app are you talking about?

**Comment by yousefsayedd1** [comment]
@yousefsayedd1  lovely-movies

**Comment by behnamazimi** [comment]
Feel free to send a PR.

**Comment by avanishEpam** [comment]
@behnamazimi I added PR for this issue. You can assign this to me and Merge this PR.

**Comment by behnamazimi** [comment]
the change was not necessary.
